 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Acesso;
import util.ControlaConexao;

/**
 *
 * @author dev
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public void IniciaTela(Acesso acesso) {

        new TelaPrincipal(acesso).setVisible(true);
        // TelaPrincipal telaPrincipal = new TelaPrincipal(acesso);
        //telaPrincipal.setVisible(true);
        super.setEnabled(true);
        dispose();

    }

    public void logar() throws ClassNotFoundException {

        Acesso acesso = new Acesso();
        acesso.setUsuario(campoUsuario.getText());
        acesso.setSenha(new String(campoSenha.getPassword()));
        acesso.setHost(campoServidor.getText());

        ControlaConexao.getConexaoUser(acesso); // catch valida usuario sen
        System.out.println("View.TelaLogin.logar()" + acesso);
        ControlaConexao.fecharConexao(ControlaConexao.getConexaoUser(acesso));
        if (ControlaConexao.getConexaoUser(acesso).equals(null)) {
            //
        } else {
            IniciaTela(acesso);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeEScola = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        campoServidor = new javax.swing.JTextField();
        ImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        NomeEScola.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        NomeEScola.setForeground(new java.awt.Color(25, 25, 117));
        NomeEScola.setText("Centro Educacional Lápis de Cor");
        getContentPane().add(NomeEScola);
        NomeEScola.setBounds(230, 70, 400, 29);

        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(campoUsuario);
        campoUsuario.setBounds(170, 190, 250, 40);
        getContentPane().add(campoSenha);
        campoSenha.setBounds(440, 190, 250, 40);

        jButton1.setBackground(new java.awt.Color(38, 108, 177));
        jButton1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Logar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 250, 520, 50);

        botaoSair.setBackground(new java.awt.Color(38, 108, 177));
        botaoSair.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        botaoSair.setForeground(java.awt.Color.white);
        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSair);
        botaoSair.setBounds(710, 390, 110, 50);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/senha4.png"))); // NOI18N
        jLabel1.setText("SENHA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 150, 130, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 25, 117));
        jLabel2.setText("Servidor:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 10, 60, 18);

        usuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        usuario.setForeground(java.awt.Color.white);
        usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        usuario.setText("USUÁRIO");
        getContentPane().add(usuario);
        usuario.setBounds(170, 150, 150, 29);

        campoServidor.setText("localhost");
        getContentPane().add(campoServidor);
        campoServidor.setBounds(600, 0, 230, 30);

        ImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tela_principal.jpg"))); // NOI18N
        getContentPane().add(ImagemFundo);
        ImagemFundo.setBounds(0, 0, 876, 465);

        setSize(new java.awt.Dimension(885, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            logar();
        } catch (ClassNotFoundException ex) {
            // Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagemFundo;
    private javax.swing.JLabel NomeEScola;
    private javax.swing.JButton botaoSair;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoServidor;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
